# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170322_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sync_exercises',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_nutrition',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_weight',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
